#ifndef W21_INPUT_H
 #define W21_INPUT_H

#include <stdsoap2.h>

int cw21rd_AutoDetect(struct soap *, const char *, size_t);
int cw21rd_BhaRun(struct soap *, const char *, size_t);
int cw21rd_CementJob(struct soap *, const char *, size_t);
int cw21rd_CementJobEvaluation(struct soap *, const char *, size_t);
int cw21rd_Channel(struct soap *, const char *, size_t);
int cw21rd_ChannelKind(struct soap *, const char *, size_t);
int cw21rd_ChannelKindDictionary(struct soap *, const char *, size_t);
int cw21rd_ChannelSet(struct soap *, const char *, size_t);
int cw21rd_CuttingsGeology(struct soap *, const char *, size_t);
int cw21rd_CuttingsGeologyInterval(struct soap *, const char *, size_t);
int cw21rd_DepthRegImage(struct soap *, const char *, size_t);
int cw21rd_DownholeComponent(struct soap *, const char *, size_t);
int cw21rd_DrillReport(struct soap *, const char *, size_t);
int cw21rd_ErrorTerm(struct soap *, const char *, size_t);
int cw21rd_ErrorTermDictionary(struct soap *, const char *, size_t);
int cw21rd_FluidsReport(struct soap *, const char *, size_t);
int cw21rd_InterpretedGeology(struct soap *, const char *, size_t);
int cw21rd_InterpretedGeologyInterval(struct soap *, const char *, size_t);
int cw21rd_Log(struct soap *, const char *, size_t);
int cw21rd_LoggingToolKind(struct soap *, const char *, size_t);
int cw21rd_LoggingToolKindDictionary(struct soap *, const char *, size_t);
int cw21rd_MudLogReport(struct soap *, const char *, size_t);
int cw21rd_MudlogReportInterval(struct soap *, const char *, size_t);
int cw21rd_OpsReport(struct soap *, const char *, size_t);
int cw21rd_PPFGChannel(struct soap *, const char *, size_t);
int cw21rd_PPFGChannelSet(struct soap *, const char *, size_t);
int cw21rd_PPFGLog(struct soap *, const char *, size_t);
int cw21rd_Rig(struct soap *, const char *, size_t);
int cw21rd_RigUtilization(struct soap *, const char *, size_t);
int cw21rd_Risk(struct soap *, const char *, size_t);
int cw21rd_ShowEvaluation(struct soap *, const char *, size_t);
int cw21rd_ShowEvaluationInterval(struct soap *, const char *, size_t);
int cw21rd_StimJob(struct soap *, const char *, size_t);
int cw21rd_StimJobStage(struct soap *, const char *, size_t);
int cw21rd_StimPerforationCluster(struct soap *, const char *, size_t);
int cw21rd_SurveyProgram(struct soap *, const char *, size_t);
int cw21rd_Target(struct soap *, const char *, size_t);
int cw21rd_ToolErrorModel(struct soap *, const char *, size_t);
int cw21rd_ToolErrorModelDictionary(struct soap *, const char *, size_t);
int cw21rd_Trajectory(struct soap *, const char *, size_t);
int cw21rd_TrajectoryStation(struct soap *, const char *, size_t);
int cw21rd_Tubular(struct soap *, const char *, size_t);
int cw21rd_WeightingFunction(struct soap *, const char *, size_t);
int cw21rd_WeightingFunctionDictionary(struct soap *, const char *, size_t);
int cw21rd_Well(struct soap *, const char *, size_t);
int cw21rd_Wellbore(struct soap *, const char *, size_t);
int cw21rd_WellboreCompletion(struct soap *, const char *, size_t);
int cw21rd_WellboreGeology(struct soap *, const char *, size_t);
int cw21rd_WellboreGeometry(struct soap *, const char *, size_t);
int cw21rd_WellboreGeometrySection(struct soap *, const char *, size_t);
int cw21rd_WellboreMarker(struct soap *, const char *, size_t);
int cw21rd_WellboreMarkerSet(struct soap *, const char *, size_t);
int cw21rd_WellCMLedger(struct soap *, const char *, size_t);
int cw21rd_WellCompletion(struct soap *, const char *, size_t);

int cw21rd_AutoDetect_from_file(struct soap *, const char *);
int cw21rd_BhaRun_from_file(struct soap *, const char *);
int cw21rd_CementJob_from_file(struct soap *, const char *);
int cw21rd_CementJobEvaluation_from_file(struct soap *, const char *);
int cw21rd_Channel_from_file(struct soap *, const char *);
int cw21rd_ChannelKind_from_file(struct soap *, const char *);
int cw21rd_ChannelKindDictionary_from_file(struct soap *, const char *);
int cw21rd_ChannelSet_from_file(struct soap *, const char *);
int cw21rd_CuttingsGeology_from_file(struct soap *, const char *);
int cw21rd_CuttingsGeologyInterval_from_file(struct soap *, const char *);
int cw21rd_DepthRegImage_from_file(struct soap *, const char *);
int cw21rd_DownholeComponent_from_file(struct soap *, const char *);
int cw21rd_DrillReport_from_file(struct soap *, const char *);
int cw21rd_ErrorTerm_from_file(struct soap *, const char *);
int cw21rd_ErrorTermDictionary_from_file(struct soap *, const char *);
int cw21rd_FluidsReport_from_file(struct soap *, const char *);
int cw21rd_InterpretedGeology_from_file(struct soap *, const char *);
int cw21rd_InterpretedGeologyInterval_from_file(struct soap *, const char *);
int cw21rd_Log_from_file(struct soap *, const char *);
int cw21rd_LoggingToolKind_from_file(struct soap *, const char *);
int cw21rd_LoggingToolKindDictionary_from_file(struct soap *, const char *);
int cw21rd_MudLogReport_from_file(struct soap *, const char *);
int cw21rd_MudlogReportInterval_from_file(struct soap *, const char *);
int cw21rd_OpsReport_from_file(struct soap *, const char *);
int cw21rd_PPFGChannel_from_file(struct soap *, const char *);
int cw21rd_PPFGChannelSet_from_file(struct soap *, const char *);
int cw21rd_PPFGLog_from_file(struct soap *, const char *);
int cw21rd_Rig_from_file(struct soap *, const char *);
int cw21rd_RigUtilization_from_file(struct soap *, const char *);
int cw21rd_Risk_from_file(struct soap *, const char *);
int cw21rd_ShowEvaluation_from_file(struct soap *, const char *);
int cw21rd_ShowEvaluationInterval_from_file(struct soap *, const char *);
int cw21rd_StimJob_from_file(struct soap *, const char *);
int cw21rd_StimJobStage_from_file(struct soap *, const char *);
int cw21rd_StimPerforationCluster_from_file(struct soap *, const char *);
int cw21rd_SurveyProgram_from_file(struct soap *, const char *);
int cw21rd_Target_from_file(struct soap *, const char *);
int cw21rd_ToolErrorModel_from_file(struct soap *, const char *);
int cw21rd_ToolErrorModelDictionary_from_file(struct soap *, const char *);
int cw21rd_Trajectory_from_file(struct soap *, const char *);
int cw21rd_TrajectoryStation_from_file(struct soap *, const char *);
int cw21rd_Tubular_from_file(struct soap *, const char *);
int cw21rd_WeightingFunction_from_file(struct soap *, const char *);
int cw21rd_WeightingFunctionDictionary_from_file(struct soap *, const char *);
int cw21rd_Well_from_file(struct soap *, const char *);
int cw21rd_Wellbore_from_file(struct soap *, const char *);
int cw21rd_WellboreCompletion_from_file(struct soap *, const char *);
int cw21rd_WellboreGeology_from_file(struct soap *, const char *);
int cw21rd_WellboreGeometry_from_file(struct soap *, const char *);
int cw21rd_WellboreGeometrySection_from_file(struct soap *, const char *);
int cw21rd_WellboreMarker_from_file(struct soap *, const char *);
int cw21rd_WellboreMarkerSet_from_file(struct soap *, const char *);
int cw21rd_WellCMLedger_from_file(struct soap *, const char *);
int cw21rd_WellCompletion_from_file(struct soap *, const char *);

#endif