/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_w21parser_W21ParserLoader */

#ifndef _Included_org_w21parser_W21ParserLoader
#define _Included_org_w21parser_W21ParserLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniInGetObjectName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_w21parser_W21ParserLoader_jniInGetObjectName
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniInit
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniInit
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniClose
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniLoadSoapXmlStrict
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniLoadSoapXmlStrict
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniLoadSoapXmlIgnoreNS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniLoadSoapXmlIgnoreNS
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniInputRulesValidatorEnable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniInputRulesValidatorEnable
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniInputRulesValidatorDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniInputRulesValidatorDisable
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadBhaRunFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadBhaRunFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadCementJobFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadCementJobFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadCementJobEvaluationFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadCementJobEvaluationFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadChannelFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadChannelFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadChannelKindFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadChannelKindFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadChannelKindDictionaryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadChannelKindDictionaryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadChannelSetFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadChannelSetFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadCuttingsGeologyFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadCuttingsGeologyFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadCuttingsGeologyIntervalFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadCuttingsGeologyIntervalFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadDepthRegImageFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadDepthRegImageFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadDownholeComponentFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadDownholeComponentFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadDrillReportFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadDrillReportFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadErrorTermFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadErrorTermFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadErrorTermDictionaryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadErrorTermDictionaryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadFluidsReportFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadFluidsReportFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadInterpretedGeologyFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadInterpretedGeologyFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadInterpretedGeologyIntervalFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadInterpretedGeologyIntervalFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadLogFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadLogFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadLoggingToolKindFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadLoggingToolKindFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadLoggingToolKindDictionaryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadLoggingToolKindDictionaryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadMudLogReportFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadMudLogReportFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadMudlogReportIntervalFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadMudlogReportIntervalFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadOpsReportFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadOpsReportFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadPPFGChannelFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadPPFGChannelFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadPPFGChannelSetFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadPPFGChannelSetFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadPPFGLogFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadPPFGLogFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadRigFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadRigFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadRigUtilizationFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadRigUtilizationFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadRiskFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadRiskFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadShowEvaluationFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadShowEvaluationFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadShowEvaluationIntervalFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadShowEvaluationIntervalFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadStimJobFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadStimJobFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadStimJobStageFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadStimJobStageFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadStimPerforationClusterFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadStimPerforationClusterFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadSurveyProgramFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadSurveyProgramFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadTargetFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadTargetFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadToolErrorModelFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadToolErrorModelFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadToolErrorModelDictionaryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadToolErrorModelDictionaryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadTrajectoryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadTrajectoryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadTrajectoryStationFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadTrajectoryStationFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadTubularFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadTubularFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWeightingFunctionFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWeightingFunctionFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWeightingFunctionDictionaryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWeightingFunctionDictionaryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreCompletionFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreCompletionFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreGeologyFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreGeologyFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreGeometryFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreGeometryFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreGeometrySectionFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreGeometrySectionFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreMarkerFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreMarkerFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellboreMarkerSetFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellboreMarkerSetFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellCMLedgerFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellCMLedgerFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniReadWellCompletionFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniReadWellCompletionFromByteBuffer
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniW21Recycle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniW21Recycle
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParse
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseBhaRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseBhaRun
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseCementJob
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseCementJob
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseCementJobEvaluation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseCementJobEvaluation
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseChannelKind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseChannelKind
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseChannelKindDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseChannelKindDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseChannelSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseChannelSet
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseCuttingsGeology
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseCuttingsGeology
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseCuttingsGeologyInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseCuttingsGeologyInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseDepthRegImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseDepthRegImage
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseDownholeComponent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseDownholeComponent
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseDrillReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseDrillReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseErrorTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseErrorTerm
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseErrorTermDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseErrorTermDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseFluidsReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseFluidsReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseInterpretedGeology
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseInterpretedGeology
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseInterpretedGeologyInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseInterpretedGeologyInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseLog
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseLoggingToolKind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseLoggingToolKind
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseLoggingToolKindDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseLoggingToolKindDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseMudLogReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseMudLogReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseMudlogReportInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseMudlogReportInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseOpsReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseOpsReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParsePPFGChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParsePPFGChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParsePPFGChannelSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParsePPFGChannelSet
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParsePPFGLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParsePPFGLog
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseRig
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseRig
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseRigUtilization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseRigUtilization
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseRisk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseRisk
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseShowEvaluation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseShowEvaluation
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseShowEvaluationInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseShowEvaluationInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseStimJob
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseStimJob
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseStimJobStage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseStimJobStage
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseStimPerforationCluster
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseStimPerforationCluster
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseSurveyProgram
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseSurveyProgram
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseTarget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseTarget
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseToolErrorModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseToolErrorModel
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseToolErrorModelDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseToolErrorModelDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseTrajectory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseTrajectory
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseTrajectoryStation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseTrajectoryStation
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseTubular
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseTubular
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWeightingFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWeightingFunction
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWeightingFunctionDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWeightingFunctionDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWell
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellbore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellbore
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellboreCompletion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellboreCompletion
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellboreGeology
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellboreGeology
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellboreGeometry
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellboreGeometry
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellboreGeometrySection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellboreGeometrySection
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellboreMarker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellboreMarker
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellboreMarkerSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellboreMarkerSet
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellCMLedger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellCMLedger
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseWellCompletion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseWellCompletion
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJson
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJson
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonBhaRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonBhaRun
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonCementJob
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonCementJob
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonCementJobEvaluation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonCementJobEvaluation
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonChannelKind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonChannelKind
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonChannelKindDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonChannelKindDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonChannelSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonChannelSet
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonCuttingsGeology
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonCuttingsGeology
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonCuttingsGeologyInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonCuttingsGeologyInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonDepthRegImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonDepthRegImage
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonDownholeComponent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonDownholeComponent
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonDrillReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonDrillReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonErrorTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonErrorTerm
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonErrorTermDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonErrorTermDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonFluidsReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonFluidsReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonInterpretedGeology
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonInterpretedGeology
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonInterpretedGeologyInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonInterpretedGeologyInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonLog
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonLoggingToolKind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonLoggingToolKind
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonLoggingToolKindDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonLoggingToolKindDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonMudLogReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonMudLogReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonMudlogReportInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonMudlogReportInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonOpsReport
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonOpsReport
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonPPFGChannel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonPPFGChannel
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonPPFGChannelSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonPPFGChannelSet
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonPPFGLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonPPFGLog
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonRig
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonRig
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonRigUtilization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonRigUtilization
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonRisk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonRisk
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonShowEvaluation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonShowEvaluation
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonShowEvaluationInterval
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonShowEvaluationInterval
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonStimJob
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonStimJob
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonStimJobStage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonStimJobStage
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonStimPerforationCluster
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonStimPerforationCluster
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonSurveyProgram
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonSurveyProgram
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonTarget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonTarget
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonToolErrorModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonToolErrorModel
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonToolErrorModelDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonToolErrorModelDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonTrajectory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonTrajectory
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonTrajectoryStation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonTrajectoryStation
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonTubular
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonTubular
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWeightingFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWeightingFunction
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWeightingFunctionDictionary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWeightingFunctionDictionary
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWell
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellbore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellbore
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellboreCompletion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellboreCompletion
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellboreGeology
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellboreGeology
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellboreGeometry
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellboreGeometry
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellboreGeometrySection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellboreGeometrySection
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellboreMarker
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellboreMarker
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellboreMarkerSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellboreMarkerSet
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellCMLedger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellCMLedger
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniParseJsonWellCompletion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_w21parser_W21ParserLoader_jniParseJsonWellCompletion
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniBeginRead
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniBeginRead
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniEndRead
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniEndRead
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatReadTotalCycles
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatReadTotalCycles
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatReadTotalNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatReadTotalNanos
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatReadMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatReadMem
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatParseTotalCycles
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatParseTotalCycles
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatParseTotalNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatParseTotalNanos
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatParseMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatParseMem
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatParseJsonTotalCycles
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatParseJsonTotalCycles
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatParseJsonTotalNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatParseJsonTotalNanos
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatParseJsonMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatParseJsonMem
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatSummaryTotalCycles
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatSummaryTotalCycles
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatSummaryTotalNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatSummaryTotalNanos
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatSummaryTotalMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_w21parser_W21ParserLoader_jniStatSummaryTotalMem
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatCosts
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatCosts
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatStrings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatStrings
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatShorts
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatShorts
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatInts
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatInts
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatLong64s
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatLong64s
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatEnums
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatEnums
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatArrays
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatArrays
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatBooleans
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatBooleans
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatDoubles
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatDoubles
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatDateTimes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatDateTimes
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatMeasures
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatMeasures
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatEventTypes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatEventTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_w21parser_W21ParserLoader
 * Method:    jniStatTotal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_w21parser_W21ParserLoader_jniStatTotal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
