/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_w21parser_W21ParserLoader_W21OutputType */

#ifndef _Included_org_w21parser_W21ParserLoader_W21OutputType
#define _Included_org_w21parser_W21ParserLoader_W21OutputType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
